# Global --------------------------
variables:
    PIP_DOWNLOAD_DIR: ".pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - pubs

# Jobs templates ------------------

.install-deps-template: &install-deps
  before_script:
    - sed -i "/^version/s/\(.*\)/version = \"$CI_COMMIT_REF_NAME\"/" pyproject.toml
    - cat pyproject.toml
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - $HOME/.poetry/bin/poetry config virtualenvs.in-project true
    - $HOME/.poetry/bin/poetry config repositories.gl https://gitlab.com/api/v4/projects/22398142/packages/pypi
    - $HOME/.poetry/bin/poetry config --list
    - $HOME/.poetry/bin/poetry install -vv

.pub-template: &pub
  <<: *install-deps
  stage: pubs
  script:
      - env
      - $HOME/.poetry/bin/poetry build
      - $HOME/.poetry/bin/poetry publish -r gl -u "$GITLAB_PYPI_NAME" -p "$GITLAB_PYPI_PWD"
  only:
    - tags

python-pub:
  <<: *pub
  image: python:3.8
