image: python:3.8
# Global --------------------------
variables:
    PIP_DOWNLOAD_DIR: ".pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - prepare
  - pubs
  - pypi

# Jobs templates ------------------

.install-deps-template: &install-deps
  stage: prepare
  script:
    - sed -i "/^version/s/\(.*\)/version = \"$CI_COMMIT_REF_NAME\"/" pyproject.toml
    - cat pyproject.toml
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - $HOME/.poetry/bin/poetry config virtualenvs.in-project true
    - $HOME/.poetry/bin/poetry config repositories.gl https://gitlab.com/api/v4/projects/27867877/packages/pypi
    - $HOME/.poetry/bin/poetry config --list
    - $HOME/.poetry/bin/poetry install -vv
  only:
    - tags

.pub-template: &pub
  stage: pubs
  script:
      - env
      - $HOME/.poetry/bin/poetry build
      - $HOME/.poetry/bin/poetry publish -r gl -u "$GITLAB_PYPI_NAME" -p "$GITLAB_PYPI_PWD"
  only:
    - tags

.pub-pypi: &pypi
  stage: pypi
  script:
      - POETRY_PYPI_TOKEN_PYPI=$PYPI_TOKEN $HOME/.poetry/bin/poetry publish
  only:
      - /^[0-9]+[.][0-9]+([.][0-9]+)?$/

install-depends:
  <<: *install-deps

python-pub:
  <<: *pub

pypi-pub:
  <<: *pypi
