
batch_size: 64
test_batch_size: 1000
epochs: 14
lr: 1.0
gamma: 0.7
no_cuda: False

trainer:
  resume: false
  ckpt: outputs/2021-02-07/01-45-44/checkpoint
  wandb: ${wandb}

wandb:
  log: false
  project: "jammy"
  name: "hydra_mnist"
  tags:
    _ "jamtorch"
    _ "trainer"
  notes:
    "this is an simple setup experiment to test the flexible trainer"
  entity: "qinsheng"
