
trainer:
  resume: true
  ckpt: outputs/2021-02-07/01-45-44/checkpoint
  ckptDir: 
  epochs: 15
  fp16: false
  ema: true
  ema_beta: 0.9
  ema_num_warm: 1
  ema_num_every: 10

  eval_epoch: 1
  eval_iter: -1


