
trainer:
  resume: true
  ckpt: outputs/2021-02-07/01-45-44/checkpoint
  ckptDir: 
  epochs: 15
  fp16: false
  ewa: true
  ewa_beta: 0.9
  ewa_num_warm: 1
  ewa_num_every: 10

  eval_epoch: 1
  eval_iter: -1


